services:
  traefik:
    image: traefik:v2.10
    platform: linux/arm64/v8
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
    ports:
      - '80:80'
      - '443:443'
      - '8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs-traefik.yml:/etc/traefik/dynamic/certs-traefik.yml
      - ./certs:/certs
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.denv.localhost`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    networks:
      - proxy

  mailpit:
    image: axllent/mailpit
    platform: linux/arm64
    ports:
      - '8025'
      - '1025:1025'
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.rule=Host(`mailpit.denv.localhost`)
      - traefik.http.services.mailpit.loadbalancer.server.port=8025
    networks:
      - proxy
    depends_on:
      - traefik

  portainer:
    image: portainer/portainer-ce:2.18.4-alpine
    platform: linux/arm64
    ports:
      - '9000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.denv.localhost`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy
    depends_on:
      - traefik

volumes:
  portainer_data: {}

networks:
  proxy:
    driver: bridge
