services:
  traefik:
    image: traefik:v3.4.4
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --ping=true
      - --entryPoints.http.address=:80
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
      - TRAEFIK_ACCESS_LOG=true
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entryPoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailpit:
    image: axllent/mailpit:v1.27.1
    restart: unless-stopped
    ports:
      - '8025'
      - '1025:1025'
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.rule=Host(`mailpit.localhost`)
      - traefik.http.services.mailpit.loadbalancer.server.port=8025
    networks:
      - proxy
    depends_on:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 3

  portainer:
    image: portainer/portainer-ce:2.31.3-alpine
    restart: unless-stopped
    ports:
      - '9000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy
    depends_on:
      - traefik
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  portainer_data: {}

networks:
  proxy:
    driver: bridge
